// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RentApp.Infrastructure.Persistence;

#nullable disable

namespace RentApp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261002160044_AddPaymentsAndReceipts")]
    partial class AddPaymentsAndReceipts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RentApp.Domain.Audit.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .HasMaxLength(256)
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("entity_type");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("ix_audit_logs_actor_user_id");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_logs_entity_type_entity_id");

                    b.HasIndex("OrganizationId", "CreatedAt")
                        .HasDatabaseName("ix_audit_logs_organization_id_created_at");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("RentApp.Domain.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("revoked_reason");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("token_hash")
                        .IsFixedLength();

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_refresh_tokens_family_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_refresh_tokens_organization_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", null, t =>
                        {
                            t.HasCheckConstraint("ck_refresh_tokens_revocation", "(revoked_at IS NULL) = (revoked_reason IS NULL)");
                        });
                });

            modelBuilder.Entity("RentApp.Domain.Organizations.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("Asia/Kolkata")
                        .HasColumnName("time_zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_organizations_owner_user_id");

                    b.ToTable("organizations", null, t =>
                        {
                            t.HasCheckConstraint("ck_organizations_status", "status IN ('Active', 'Suspended')");
                        });
                });

            modelBuilder.Entity("RentApp.Domain.Payments.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("method");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date")
                        .HasColumnName("payment_date");

                    b.Property<Guid?>("RecordedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by_user_id");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("VoidReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("void_reason");

                    b.Property<DateTimeOffset?>("VoidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("voided_at");

                    b.Property<Guid?>("VoidedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("voided_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasAlternateKey("Id", "OrganizationId")
                        .HasName("ak_payments_id_organization_id");

                    b.HasIndex("RecordedByUserId")
                        .HasDatabaseName("ix_payments_recorded_by_user_id");

                    b.HasIndex("VoidedByUserId")
                        .HasDatabaseName("ix_payments_voided_by_user_id");

                    b.HasIndex("OrganizationId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_payments_organization_id_idempotency_key")
                        .HasFilter("idempotency_key IS NOT NULL");

                    b.HasIndex("OrganizationId", "PaymentDate")
                        .HasDatabaseName("ix_payments_organization_id_payment_date");

                    b.HasIndex("TenantId", "OrganizationId")
                        .HasDatabaseName("ix_payments_tenant_id_organization_id");

                    b.HasIndex("TenantId", "PaymentDate")
                        .HasDatabaseName("ix_payments_tenant_id_payment_date");

                    b.ToTable("payments", null, t =>
                        {
                            t.HasCheckConstraint("ck_payments_amount_positive", "amount > 0");

                            t.HasCheckConstraint("ck_payments_method", "method IN ('Cash', 'Upi', 'BankTransfer', 'Card', 'Other')");

                            t.HasCheckConstraint("ck_payments_status", "status IN ('Recorded', 'Voided')");

                            t.HasCheckConstraint("ck_payments_voided_has_details", "(status = 'Voided') = (voided_at IS NOT NULL AND void_reason IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("RentApp.Domain.Payments.PaymentAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AllocatedAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("allocated_amount");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<Guid>("RentChargeId")
                        .HasColumnType("uuid")
                        .HasColumnName("rent_charge_id");

                    b.HasKey("Id")
                        .HasName("pk_payment_allocations");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_payment_allocations_organization_id");

                    b.HasIndex("RentChargeId")
                        .HasDatabaseName("ix_payment_allocations_rent_charge_id");

                    b.HasIndex("PaymentId", "OrganizationId")
                        .HasDatabaseName("ix_payment_allocations_payment_id_organization_id");

                    b.HasIndex("PaymentId", "RentChargeId")
                        .IsUnique()
                        .HasDatabaseName("ix_payment_allocations_payment_id_rent_charge_id");

                    b.HasIndex("RentChargeId", "OrganizationId")
                        .HasDatabaseName("ix_payment_allocations_rent_charge_id_organization_id");

                    b.ToTable("payment_allocations", null, t =>
                        {
                            t.HasCheckConstraint("ck_payment_allocations_amount_positive", "allocated_amount > 0");
                        });
                });

            modelBuilder.Entity("RentApp.Domain.Payments.Receipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<string>("BedLabel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("bed_label");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<DateOnly>("IssuedOn")
                        .HasColumnType("date")
                        .HasColumnName("issued_on");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("method");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("organization_name");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date")
                        .HasColumnName("payment_date");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<string>("PeriodLabel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("period_label");

                    b.Property<string>("PropertyAddress")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)")
                        .HasColumnName("property_address");

                    b.Property<string>("PropertyContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("property_contact_phone");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("property_name");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("receipt_number");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference_number");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("room_number");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("tenant_name");

                    b.Property<string>("TenantPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tenant_phone");

                    b.HasKey("Id")
                        .HasName("pk_receipts");

                    b.HasIndex("PaymentId")
                        .IsUnique()
                        .HasDatabaseName("ix_receipts_payment_id");

                    b.HasIndex("OrganizationId", "ReceiptNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_receipts_organization_id_receipt_number");

                    b.HasIndex("PaymentId", "OrganizationId")
                        .HasDatabaseName("ix_receipts_payment_id_organization_id");

                    b.ToTable("receipts", null, t =>
                        {
                            t.HasCheckConstraint("ck_receipts_amount_positive", "amount > 0");

                            t.HasCheckConstraint("ck_receipts_method", "method IN ('Cash', 'Upi', 'BankTransfer', 'Card', 'Other')");
                        });
                });

            modelBuilder.Entity("RentApp.Domain.Payments.ReceiptCounter", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.Property<long>("LastNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("last_number");

                    b.HasKey("OrganizationId", "Year")
                        .HasName("pk_receipt_counters");

                    b.ToTable("receipt_counters", null, t =>
                        {
                            t.HasCheckConstraint("ck_receipt_counters_last_number_positive", "last_number > 0");
                        });
                });

            modelBuilder.Entity("RentApp.Domain.Properties.Bed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("DefaultMonthlyRent")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("default_monthly_rent");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("label");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_beds");

                    b.HasAlternateKey("Id", "RoomId", "OrganizationId")
                        .HasName("ak_beds_id_room_id_organization_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_beds_organization_id");

                    b.HasIndex("RoomId", "Label")
                        .IsUnique()
                        .HasDatabaseName("ix_beds_room_id_label")
                        .HasFilter("status <> 'Archived'");

                    b.HasIndex("RoomId", "OrganizationId")
                        .HasDatabaseName("ix_beds_room_id_organization_id");

                    b.ToTable("beds", null, t =>
                        {
                            t.HasCheckConstraint("ck_beds_default_rent_positive", "default_monthly_rent IS NULL OR default_monthly_rent > 0");

                            t.HasCheckConstraint("ck_beds_status", "status IN ('Available', 'Reserved', 'Unavailable', 'Archived')");
                        });
                });

            modelBuilder.Entity("RentApp.Domain.Properties.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("contact_phone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("postal_code");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("state");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_properties");

                    b.HasAlternateKey("Id", "OrganizationId")
                        .HasName("ak_properties_id_organization_id");

                    b.HasIndex("OrganizationId", "Status")
                        .HasDatabaseName("ix_properties_organization_id_status");

                    b.ToTable("properties", null, t =>
                        {
                            t.HasCheckConstraint("ck_properties_status", "status IN ('Active', 'Archived')");
                        });
                });

            modelBuilder.Entity("RentApp.Domain.Properties.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("room_number");

                    b.Property<string>("RoomType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("room_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_rooms");

                    b.HasAlternateKey("Id", "OrganizationId")
                        .HasName("ak_rooms_id_organization_id");

                    b.HasAlternateKey("Id", "PropertyId", "OrganizationId")
                        .HasName("ak_rooms_id_property_id_organization_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_rooms_organization_id");

                    b.HasIndex("PropertyId", "OrganizationId")
                        .HasDatabaseName("ix_rooms_property_id_organization_id");

                    b.HasIndex("PropertyId", "RoomNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_rooms_property_id_room_number")
                        .HasFilter("status <> 'Archived'");

                    b.ToTable("rooms", null, t =>
                        {
                            t.HasCheckConstraint("ck_rooms_capacity", "capacity BETWEEN 1 AND 50");

                            t.HasCheckConstraint("ck_rooms_status", "status IN ('Active', 'Unavailable', 'Archived')");
                        });
                });

            modelBuilder.Entity("RentApp.Domain.Rent.RentCharge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AdjustedAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("adjusted_amount");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<decimal>("BalanceAmount")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("balance_amount")
                        .HasComputedColumnSql("amount - paid_amount - adjusted_amount", true);

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<decimal>("PaidAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("paid_amount");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date")
                        .HasColumnName("period_end");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("period_start");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<Guid>("RentAgreementId")
                        .HasColumnType("uuid")
                        .HasColumnName("rent_agreement_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_rent_charges");

                    b.HasAlternateKey("Id", "OrganizationId")
                        .HasName("ak_rent_charges_id_organization_id");

                    b.HasIndex("OrganizationId", "DueDate")
                        .HasDatabaseName("ix_rent_charges_outstanding_by_due_date")
                        .HasFilter("cancelled_at IS NULL AND balance_amount > 0");

                    b.HasIndex("OrganizationId", "PeriodStart")
                        .HasDatabaseName("ix_rent_charges_organization_id_period_start");

                    b.HasIndex("PropertyId", "DueDate")
                        .HasDatabaseName("ix_rent_charges_property_id_due_date");

                    b.HasIndex("RentAgreementId", "PeriodStart")
                        .IsUnique()
                        .HasDatabaseName("ix_rent_charges_rent_agreement_id_period_start");

                    b.HasIndex("TenantId", "DueDate")
                        .HasDatabaseName("ix_rent_charges_tenant_id_due_date");

                    b.HasIndex("RentAgreementId", "TenantId", "PropertyId", "OrganizationId")
                        .HasDatabaseName("ix_rent_charges_rent_agreement_id_tenant_id_property_id_organi");

                    b.ToTable("rent_charges", null, t =>
                        {
                            t.HasCheckConstraint("ck_rent_charges_adjusted_non_negative", "adjusted_amount >= 0");

                            t.HasCheckConstraint("ck_rent_charges_amount_positive", "amount > 0");

                            t.HasCheckConstraint("ck_rent_charges_not_over_settled", "paid_amount + adjusted_amount <= amount");

                            t.HasCheckConstraint("ck_rent_charges_paid_non_negative", "paid_amount >= 0");

                            t.HasCheckConstraint("ck_rent_charges_period", "period_end >= period_start");
                        });
                });

            modelBuilder.Entity("RentApp.Domain.Rent.RentChargeAdjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reason");

                    b.Property<Guid>("RentChargeId")
                        .HasColumnType("uuid")
                        .HasColumnName("rent_charge_id");

                    b.HasKey("Id")
                        .HasName("pk_rent_charge_adjustments");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_rent_charge_adjustments_created_by_user_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_rent_charge_adjustments_organization_id");

                    b.HasIndex("RentChargeId")
                        .HasDatabaseName("ix_rent_charge_adjustments_rent_charge_id");

                    b.HasIndex("RentChargeId", "OrganizationId")
                        .HasDatabaseName("ix_rent_charge_adjustments_rent_charge_id_organization_id");

                    b.ToTable("rent_charge_adjustments", null, t =>
                        {
                            t.HasCheckConstraint("ck_rent_charge_adjustments_amount_positive", "amount > 0");
                        });
                });

            modelBuilder.Entity("RentApp.Domain.Tenants.RentAgreement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BedId")
                        .HasColumnType("uuid")
                        .HasColumnName("bed_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("EndReason")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("end_reason");

                    b.Property<decimal>("MonthlyRent")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("monthly_rent");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<int>("RentDueDay")
                        .HasColumnType("integer")
                        .HasColumnName("rent_due_day");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<decimal>("SecurityDeposit")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("security_deposit");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_rent_agreements");

                    b.HasAlternateKey("Id", "TenantId", "PropertyId", "OrganizationId")
                        .HasName("ak_rent_agreements_id_tenant_id_property_id_organization_id");

                    b.HasIndex("BedId")
                        .IsUnique()
                        .HasDatabaseName("ux_rent_agreements_active_bed_id")
                        .HasFilter("status = 'Active'");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ux_rent_agreements_active_tenant_id")
                        .HasFilter("status = 'Active'");

                    b.HasIndex("OrganizationId", "Status")
                        .HasDatabaseName("ix_rent_agreements_organization_id_status");

                    b.HasIndex("PropertyId", "Status")
                        .HasDatabaseName("ix_rent_agreements_property_id_status");

                    b.HasIndex("RoomId", "Status")
                        .HasDatabaseName("ix_rent_agreements_room_id_status");

                    b.HasIndex("TenantId", "OrganizationId")
                        .HasDatabaseName("ix_rent_agreements_tenant_id_organization_id");

                    b.HasIndex("BedId", "RoomId", "OrganizationId")
                        .HasDatabaseName("ix_rent_agreements_bed_id_room_id_organization_id");

                    b.HasIndex("RoomId", "PropertyId", "OrganizationId")
                        .HasDatabaseName("ix_rent_agreements_room_id_property_id_organization_id");

                    b.ToTable("rent_agreements", null, t =>
                        {
                            t.HasCheckConstraint("ck_rent_agreements_dates", "end_date IS NULL OR end_date >= start_date");

                            t.HasCheckConstraint("ck_rent_agreements_deposit_non_negative", "security_deposit >= 0");

                            t.HasCheckConstraint("ck_rent_agreements_due_day", "rent_due_day BETWEEN 1 AND 31");

                            t.HasCheckConstraint("ck_rent_agreements_end_reason", "end_reason IS NULL OR end_reason IN ('MovedOut', 'Transferred', 'Cancelled')");

                            t.HasCheckConstraint("ck_rent_agreements_ended_has_end_date", "(status = 'Ended') = (end_date IS NOT NULL)");

                            t.HasCheckConstraint("ck_rent_agreements_ended_has_reason", "(status = 'Ended') = (end_reason IS NOT NULL)");

                            t.HasCheckConstraint("ck_rent_agreements_rent_positive", "monthly_rent > 0");

                            t.HasCheckConstraint("ck_rent_agreements_status", "status IN ('Active', 'Ended')");
                        });
                });

            modelBuilder.Entity("RentApp.Domain.Tenants.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("EmergencyContactName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("emergency_contact_name");

                    b.Property<string>("EmergencyContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("emergency_contact_phone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("full_name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PermanentAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("permanent_address");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("PhoneDigits")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_digits");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasAlternateKey("Id", "OrganizationId")
                        .HasName("ak_tenants_id_organization_id");

                    b.HasIndex("OrganizationId", "PhoneDigits")
                        .HasDatabaseName("ix_tenants_organization_id_phone_digits");

                    b.HasIndex("OrganizationId", "Status", "FullName")
                        .HasDatabaseName("ix_tenants_organization_id_status_full_name");

                    b.ToTable("tenants", null, t =>
                        {
                            t.HasCheckConstraint("ck_tenants_status", "status IN ('Active', 'Archived')");
                        });
                });

            modelBuilder.Entity("RentApp.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<int>("Permissions")
                        .HasColumnType("integer")
                        .HasColumnName("permissions");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ix_users_normalized_email");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_users_organization_id");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_owner_has_no_permissions", "role <> 'Owner' OR permissions = 0");

                            t.HasCheckConstraint("ck_users_permissions_range", "permissions >= 0 AND permissions <= 31");

                            t.HasCheckConstraint("ck_users_role", "role IN ('Owner', 'Staff')");

                            t.HasCheckConstraint("ck_users_status", "status IN ('Active', 'Disabled')");
                        });
                });

            modelBuilder.Entity("RentApp.Domain.Audit.AuditLog", b =>
                {
                    b.HasOne("RentApp.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_audit_logs_users_actor_user_id");

                    b.HasOne("RentApp.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_logs_organizations_organization_id");
                });

            modelBuilder.Entity("RentApp.Domain.Identity.RefreshToken", b =>
                {
                    b.HasOne("RentApp.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_organizations_organization_id");

                    b.HasOne("RentApp.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");
                });

            modelBuilder.Entity("RentApp.Domain.Organizations.Organization", b =>
                {
                    b.HasOne("RentApp.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_organizations_users_owner_user_id");
                });

            modelBuilder.Entity("RentApp.Domain.Payments.Payment", b =>
                {
                    b.HasOne("RentApp.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("RecordedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_payments_users_recorded_by_user_id");

                    b.HasOne("RentApp.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("VoidedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_payments_users_voided_by_user_id");

                    b.HasOne("RentApp.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_tenants_tenant_id_organization_id");
                });

            modelBuilder.Entity("RentApp.Domain.Payments.PaymentAllocation", b =>
                {
                    b.HasOne("RentApp.Domain.Payments.Payment", null)
                        .WithMany()
                        .HasForeignKey("PaymentId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payment_allocations_payments_payment_id_organization_id");

                    b.HasOne("RentApp.Domain.Rent.RentCharge", null)
                        .WithMany()
                        .HasForeignKey("RentChargeId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payment_allocations_rent_charges_rent_charge_id_organizatio");
                });

            modelBuilder.Entity("RentApp.Domain.Payments.Receipt", b =>
                {
                    b.HasOne("RentApp.Domain.Payments.Payment", null)
                        .WithMany()
                        .HasForeignKey("PaymentId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_receipts_payments_payment_id_organization_id");
                });

            modelBuilder.Entity("RentApp.Domain.Payments.ReceiptCounter", b =>
                {
                    b.HasOne("RentApp.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_receipt_counters_organizations_organization_id");
                });

            modelBuilder.Entity("RentApp.Domain.Properties.Bed", b =>
                {
                    b.HasOne("RentApp.Domain.Properties.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_beds_rooms_room_id_organization_id");
                });

            modelBuilder.Entity("RentApp.Domain.Properties.Property", b =>
                {
                    b.HasOne("RentApp.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_properties_organizations_organization_id");
                });

            modelBuilder.Entity("RentApp.Domain.Properties.Room", b =>
                {
                    b.HasOne("RentApp.Domain.Properties.Property", null)
                        .WithMany()
                        .HasForeignKey("PropertyId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rooms_properties_property_id_organization_id");
                });

            modelBuilder.Entity("RentApp.Domain.Rent.RentCharge", b =>
                {
                    b.HasOne("RentApp.Domain.Tenants.RentAgreement", null)
                        .WithMany()
                        .HasForeignKey("RentAgreementId", "TenantId", "PropertyId", "OrganizationId")
                        .HasPrincipalKey("Id", "TenantId", "PropertyId", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rent_charges_rent_agreements_rent_agreement_id_tenant_id_pr");
                });

            modelBuilder.Entity("RentApp.Domain.Rent.RentChargeAdjustment", b =>
                {
                    b.HasOne("RentApp.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_rent_charge_adjustments_users_created_by_user_id");

                    b.HasOne("RentApp.Domain.Rent.RentCharge", null)
                        .WithMany()
                        .HasForeignKey("RentChargeId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rent_charge_adjustments_rent_charges_rent_charge_id_organiz");
                });

            modelBuilder.Entity("RentApp.Domain.Tenants.RentAgreement", b =>
                {
                    b.HasOne("RentApp.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rent_agreements_tenants_tenant_id_organization_id");

                    b.HasOne("RentApp.Domain.Properties.Bed", null)
                        .WithMany()
                        .HasForeignKey("BedId", "RoomId", "OrganizationId")
                        .HasPrincipalKey("Id", "RoomId", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rent_agreements_beds_bed_id_room_id_organization_id");

                    b.HasOne("RentApp.Domain.Properties.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId", "PropertyId", "OrganizationId")
                        .HasPrincipalKey("Id", "PropertyId", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rent_agreements_rooms_room_id_property_id_organization_id");
                });

            modelBuilder.Entity("RentApp.Domain.Tenants.Tenant", b =>
                {
                    b.HasOne("RentApp.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tenants_organizations_organization_id");
                });

            modelBuilder.Entity("RentApp.Domain.Users.User", b =>
                {
                    b.HasOne("RentApp.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_organizations_organization_id");
                });
#pragma warning restore 612, 618
        }
    }
}
